apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "maildev.fullname" . }}
  labels:
    {{- include "maildev.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "maildev.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "maildev.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "maildev.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          command: ["/opt/app-root/src/bin/maildev"]
          args: ["--verbose", "--outgoing-secure", "--auto-relay"]
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
          - name: smtp-port
            containerPort: {{ .Values.ports.smtp }}
            protocol: TCP
          - name: web-port
            containerPort: {{ .Values.ports.web }}
            protocol: TCP
          env:
          - name: MAILDEV_DISABLE_WEB
            value: "{{ .Values.web.disable }}"
          {{- if or .Values.web.user .Values.web.pass}}
          - name: MAILDEV_WEB_USER
            value: "{{ .Values.web.user }}"
          - name: MAILDEV_WEB_PASS
            value: "{{ .Values.web.pass }}"
          {{- end }}
          - name: MAILDEV_SMTP_PORT
            value: "{{ .Values.ports.smtp }}"
          - name: MAILDEV_WEB_PORT
            value: "{{ .Values.ports.web }}"
          - name: MAILDEV_HTTPS
            value: "{{ .Values.https.enabled }}"
          {{- if .Values.https.key }}
          - name: MAILDEV_HTTPS_KEY
            value: "{{ .Values.https.key }}"
          {{- end }}
          {{- if .Values.https.cert }}
          - name: MAILDEV_HTTPS_CERT
            value:  "{{ .Values.https.cert }}"
          {{- end }}
          - name: MAILDEV_OUTGOING_HOST
            value: "{{ .Values.outgoing_relay.host }}"
          - name: MAILDEV_OUTGOING_PORT
            value: "{{ .Values.outgoing_relay.port }}"
          - name: MAILDEV_OUTGOING_USER
            value: "{{ .Values.outgoing_relay.user }}"
          - name: MAILDEV_OUTGOING_PASS
            value: "{{ .Values.outgoing_relay.pass }}"
          - name: MAILDEV_OUTGOING_SECURE
            value: "{{ .Values.outgoing_relay.secure }}"
          {{- if .Values.incoming }}
          - name: MAILDEV_INCOMING_USER
            value: "{{ .Values.incoming.user }}"
          - name: MAILDEV_INCOMING_PASS
            value:  "{{ .Values.incoming.pass }}"
          {{- end }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.ports.web }}
          readinessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.ports.web }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
          - name: auto-relay-rules
            mountPath: /etc/maildev
            subpath: auto-relay-rules.json
      volumes:
      - name: auto-relay-rules
        configMap:
          name: maildev-relay-rules
          items:
          - key: auto-relay-rules.json
            path: auto-relay-rules.json
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
