{{- if and (not .Values.source_secrets) (.Values.sealed_secrets ) }}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: my-token
spec:
  encryptedData:
    token: AgB3PCsZ9b52SQTRzTsG881Mj6zOmHKALfFCPInGqc/iX6aBPaU+BLWQn6qztHrnlF3/yPypebSK+0q2dLrZA1/tfAAIXBQjNdTtrNZedsE98LLNmgkpxiqabRVyjkKdU6lnBnaLC3in1gzTqPzTjhvEOIONv35BenLttwvEaTKlkuXQvhmIBEKsWbMuGu6IuqLVAm+4xfUeSRthsmibBbAGwbGpDpFTAKZjsDjSWt07IVKIyfzv0qwc/TK8LPvlD4y9p5hdIJaaHIkCZQjWTq0erbbnQhMmST2a3hjwX7QBqGIBrIMLtM9D0Yy+zhafz5RmfeU1GL5DSFZLZ4hvqR8KgOdcq/W/NpCKQhjfMwdmavxhtDMn3LhK1VfufaR67LCV4yRTXHHlgRXDImypVRI9rYvDOxTa+AbViJsX1jtCMFz6l6EchFxVUaXdaJJCqv226dlOpy8yE6mOIQ7NXZFfDbrI0Z6Z6m3oZAc9WL/ixdEXRjBn5LoorSN73BYNRD4+Kf5w17hh03wotCfUeAG7OuX32gwgvQ1PvKQzAz3aRhIRVhPKz2XveAYAMjdDz8tYQb1S9JKz0ss6TYAw7EBgreuW+fJKzlN3rfMYaVfQNxLgm+G7ch3+UJ0tm8f9TxZMqa/KrT8dpJpGIK4OExyfq6qOEtsFsFwLGO44kI8tFEo8FguqafP5qiCf4+pepjIx5+c+G01LRIUXbbdn2Ctoow==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      labels:
        credential.sync.jenkins.openshift.io: "true"
      name: my-token
    type: Opaque
{{- end }}