{{- if and (not .Values.source_secrets) (.Values.sealed_secrets ) }}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: git-auth
spec:
  encryptedData:
    password: AgB8Z5hHPzh6+1MJCnrq/h315AiUOIMiAlsVZz0xwUWkceUClyrbj92WXpSZRDq3UFKU/DIzOoPW057O4khqMCDFxqVj+cYvMSPDpb7K3UL5u2w3IC/WxQK1I05ArLWETAkUS2G5vbIk25MrEh9X4ZJxAp8H617X6EiHuvmfBI7guzfeFBiC0M3lJEoye4RmpDbVuPrwvyDlfvAvCYHsgLTyDNY6eZ1vVTO3SREL8LBuW8AlJYE65vpEzA1jUjLif0w0r55prABuVF+V8vjSQCXUSiapTT4uPPZ1m/YWwB/QZ7QSgbjQ4vu1RrfpSqnQkGh+sjAqwpMBLepUZscIAaQ1S4+xWLFGOyaYz+C8kv+BeCfMsxDHLSQ5yCH0BDcESHCo+hH9+1WmNDkckdgK4bUdsvNU8iwllLVhZBFtTt3fbcI3PQupQcoqp2ONcy5Si0OFDhqtpemdG1D3mH7dhvV79UcTFKJT41putLEvuAyEn0akKxVJ+Gwf1939rfhZZn6qGLA8FRnh2wR6jI1m6vyAjZOb6Tp1DpS1goaj78VRehTr6DDjC1lgnbthwF/ZLKG8q8cdInLbenBDoclN069bzorfOTif00mWZDZlpxnQaH1eqTpF70+neRZnxDeglQpU2r6q7O8CrwYhyH1cwyTHPc8cVbEKiJD8ijpNX5VSGovBHWgfFrK0umMnJb1FWKjQGMecJL18sXJqIaBY31FvcNaAfy0rtyW8iHe4TIyM2tOY3mI=
    username: AgAfzz2zXziYv2qKqNii3+ftYh0uqIlauDJMPrbPqEKTLf2LnyMuAfwJPS4E5wjBShGs0UXXjVXloDCIJSEdnrMf2jAaCVNzgccATQHWpdfzoz9/JUyTA95fW1eAqCr8LLJ62IQv4Ce0CcAjjb0QnCrO2kKug0LlqTqIwGbayn/vPYW4a5+hNFQo0Jg6G7zDaNEuIPHS9jnCiqM4HutNjKNWllCCxd8xrq220HXL1OiYOVKwcwmrD1MoKABGqmdSHp62E1wjCpWN4fRr+mPxALMX2au/FEnu8RiZ9Pf8dzK6qx5IjhQPVI9r2jNMYKizSATP2CvdPnoazplGtitJ1Jrsv3XvyJPYzIokAAKN0Q5h1KydLa6sy563ToJqnzFUe5Gs1HjRpyPg+uuvy+qjRssZdPvhJKFRK1RRm9ByP1EemEGC8ZZy20iFH2J1eYfRHYcK/nUfgwi0KOLbt2788vpcArsdw2d81oq/cGiIR5SDWUK44P7FOmmfvaxY2unfsqkO8eRbKtjt7dBm60mgBbOgT0T0+I8k4dw//V4s2zxOJaKxMFP62gCkE+nHX213JqGa3+QRNnyBQ+Y7f6OXXTbymgykRmEyuJ2urkZqcLhqXCWumuiWfIdaA7TJSBAtIy8SGIcHkJZhbx5EZjRjV+lL6vhxo5yGlNof/CWVK9EQCtfYcnsFvUtW7O+P/1WTTER8Ya2MH6JZiA==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      labels:
        credential.sync.jenkins.openshift.io: "true"
      name: git-auth
    type: kubernetes.io/basic-auth
{{- end }}