{{- if and (not .Values.source_secrets) (.Values.sealed_secrets ) }}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: nexus-password
spec:
  encryptedData:
    password: AgBPaeDBZqFqnWikyPSil8DQTPioe9cDbv7UsA1exjCkSXHaf+ilCQE7UlQ/b80Jr7iJ/np/crF4P6t0hAc7339HErNXKdZ00EAneiwwZsnXf1eCk4TQ1wohZE60kLPRi/OFLtP7t8fL/4c0ZYmkPoI3AUt5QI1Uqhqt9rsXlHielga+rTQq2+r1WWzX2YZ8izZ0YbgnZEs6iz08rTpuLxZlS4Z+k7RqJfxIztGY20QZwNPXJc16+x1BDLHfiy/aZjv42/qz33hBemxlgHJFVMuzdb7YTC2EaQvo1ZEpnX6GDsFhj92UWveDrgAWtr6KnQSQ3U93k5SBdNggZUrKA/unSgdzhupD9iyAht0eNp/saGlSTSE9tj6BgQsn+ciK1f+SRWqRDXB/f1i2ReIFkvDxBcDQZZCOJ2V7wgU4WmYEeSj/d2YEPDDoci+pyBqviJ6YpA/MXgC3YmLHiAmoAY95SpixW1F7CvROmdIzHOuZItOi0X2BnYgn7NazYZ2imMOfERMrbaFMXxttCbVXDPYtwqzfpuOi/pFf7NVGr1DQC6nuyoN10/Bu9RU/CnHTNRFfPdMo/tW9N6iw1dAL9C9etfvaNXuWxbY/7iKrLNJftnBziukRoOW/oC7GWiBIaUjQZj4HL3DSx31TKoA9WOd4mOdQv7wn252cJxXfnQJBVzn4BxrgVgcBBKTsE+y1C1ajOx+mTtG0a69HhaM=
    username: AgBAWwo/uSeseALML1mDaHpDSuONhWHHxeXXWsGlYdbWuI2eGo9a6ALawO99vywROgc7dZgo2McKtqam8zV/l/F9I1gg7G8fsLti6+RkOXdCYwc17DNYoqaxY6UBjRRVQF8bklBErAH8IUGh4VOE4j9z18PuzNds81b1GanFFok+6JRXfIDL/ctZQwyYCdpzJqzGWCt+4noALx/KC9osGkgrhqfC7F+ESwYYneGrKdAeZNY5Wn31aYUDMT0GAXIlAn0eJP1EcTJWEtw/VL8YC51bvm6tr7sx8j1ZJrHUdn9XkWEheolhqK03OrKLp/5kqgAzUbUClf8MtHT1+9sjQ9ZC6Omxj4WqGu3Uuk2I8UMQoPxOvFxAngWM+EkE4fZCTkLr7P8C10f5CP82eYbaZbdETCWMig1e72eb7/CdF6q71FklCQ6ei8LKM1HdBr2RuaiZRYBxAJmMPnVwecQpGN1YlyGydATLVIlO+wLP8WsOe3cWgSOFd+/HDAEx4bq+b8nUcMmAKCkWS8dx/m9IfPz7L/Q0jDoWu/o84dPWzsrwtGCmSyGxn/LFnNhlzrlfSZUUnvg+Fy/x9ayETvvs16e/v3tGcem8sWukl6FIaY2F8SDnn/5318K44yiI+5yKnb2o42VErnI3NLt2rcPCiDLIfUf+5B3RZxlB3ApEbbyTTHp4hcHOIMMxBW/ZXYAtDaw5I5taT2pDqA==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      labels:
        credential.sync.jenkins.openshift.io: "true"
      name: nexus-password
    type: kubernetes.io/basic-auth
{{- end }}